### ISSUE TITLE
Doesn't work on Java 9.0.4 and 10.0.1

### ISSUE THREAD

**Issue by sshikov** [litan/kojo#6]
Exception in thread "main" java.lang.ExceptionInInitializerError
        at net.kogics.kojo.lite.DesktopMain.main(DesktopMain.scala)
Caused by: java.lang.RuntimeException: classloader (jdk.internal.loader.ClassLoaders$AppClassLoader@6d5380c2) is not a URLClassLoader
        at scala.sys.package$.error(package.scala:27)
        at net.kogics.kojo.lite.DesktopMain$.<init>(DesktopMain.scala:23)
        at net.kogics.kojo.lite.DesktopMain$.<clinit>(DesktopMain.scala)
        ... 1 more

**Comment by litan** [comment]
Yeah, we only support Java 8 at the moment. Java 11 (and Java 10 / 9) support is planned for the future.

**Comment by litan** [comment]
Kojo 2.9.01 works with Java 8+. It ships with Java 11 bundled.
